theme: minima
title: Gartner insights into Enterprise perspective on Microservices Blog
author: Aidan Blaney
description:Thoughts and response to the content in the Gartner paper on Microservices.
